-- PitchMe production schema
create extension if not exists pgcrypto;
create type pitch_status as enum ('pending','open','contacted','responded','planned','in_progress','shipped','declined');
create type reaction_kind as enum ('supportive','love','fire','helpful','agree','not_enough');
create table companies (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, website text, logo_url text, description text, contact_email text, created_at timestamptz not null default now());
create table products (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, slug text not null, created_at timestamptz not null default now(), unique(company_id, slug));
create table pitches (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), product_id uuid not null references products(id), title text not null check (char_length(title) between 8 and 140), slug text not null, body text not null check (char_length(body) between 20 and 2000), suggested_slug text, status pitch_status not null default 'pending', support_count bigint not null default 0, submitter_note text, moderation_note text, email_milestones_sent int[] not null default '{}', last_email_milestone int, contacted_at timestamptz, company_response text, company_response_verified boolean not null default false, responded_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id, product_id, slug));
create table supports (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, fingerprint text not null, created_at timestamptz not null default now(), unique(pitch_id, fingerprint));
create table pitch_reactions (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, fingerprint text not null, reaction reaction_kind not null, created_at timestamptz not null default now(), unique(pitch_id, fingerprint));
create table comments (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, fingerprint text not null, body text not null check (char_length(body) between 1 and 1000), display_name text, approved boolean not null default false, created_at timestamptz not null default now());
create table company_responses (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, body text not null, verified boolean not null default false, received_at timestamptz, published_at timestamptz, created_at timestamptz not null default now());
create table email_milestone_events (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, milestone int not null check (milestone in (1,25,50,100,500,1000)), sent_at timestamptz not null default now(), notes text, unique(pitch_id, milestone));
create index pitches_company_idx on pitches(company_id); create index pitches_product_idx on pitches(product_id); create index pitches_support_count_idx on pitches(support_count desc); create index comments_pitch_idx on comments(pitch_id, created_at desc);

alter table companies enable row level security; alter table products enable row level security; alter table pitches enable row level security; alter table supports enable row level security; alter table pitch_reactions enable row level security; alter table comments enable row level security; alter table company_responses enable row level security; alter table email_milestone_events enable row level security;
create policy companies_public_read on companies for select using (true);
create policy products_public_read on products for select using (true);
create policy pitches_public_read on pitches for select using (status <> 'pending');
create policy comments_public_read on comments for select using (approved = true);
create policy responses_public_read on company_responses for select using (verified = true and published_at is not null);

create or replace function public.increment_support(p_pitch_id uuid, p_fingerprint text) returns bigint language plpgsql security definer set search_path = public as $$ declare new_count bigint; begin insert into supports(pitch_id,fingerprint) values(p_pitch_id,p_fingerprint) on conflict(pitch_id,fingerprint) do nothing; if found then update pitches set support_count=support_count+1,updated_at=now() where id=p_pitch_id returning support_count into new_count; else select support_count into new_count from pitches where id=p_pitch_id; end if; return coalesce(new_count,0); end; $$;
create or replace function public.add_pitch_reaction(p_pitch_id uuid,p_fingerprint text,p_reaction reaction_kind) returns boolean language plpgsql security definer set search_path = public as $$ begin if not exists(select 1 from pitches where id=p_pitch_id and status<>'pending') then return false; end if; insert into pitch_reactions(pitch_id,fingerprint,reaction) values(p_pitch_id,p_fingerprint,p_reaction) on conflict(pitch_id,fingerprint) do update set reaction=excluded.reaction; return true; end; $$;
create or replace function public.add_pitch_comment(p_pitch_id uuid,p_fingerprint text,p_body text) returns uuid language plpgsql security definer set search_path = public as $$ declare new_id uuid; begin if not exists(select 1 from pitches where id=p_pitch_id and status<>'pending') then return null; end if; if char_length(trim(p_body))<1 or char_length(trim(p_body))>1000 then return null; end if; insert into comments(pitch_id,fingerprint,body,approved) values(p_pitch_id,p_fingerprint,trim(p_body),false) returning id into new_id; return new_id; end; $$;
revoke all on function public.increment_support(uuid,text) from public,anon,authenticated; grant execute on function public.increment_support(uuid,text) to anon,authenticated;
revoke all on function public.add_pitch_reaction(uuid,text,reaction_kind) from public,anon,authenticated; grant execute on function public.add_pitch_reaction(uuid,text,reaction_kind) to anon,authenticated;
revoke all on function public.add_pitch_comment(uuid,text,text) from public,anon,authenticated; grant execute on function public.add_pitch_comment(uuid,text,text) to anon,authenticated;

-- Seed data is maintained separately after schema creation. Do not duplicate production seed rows here.
