-- PitchMe production schema. Apply through Supabase migrations; this file documents the full current schema.
create extension if not exists pgcrypto;

do $$ begin create type pitch_status as enum ('pending','open','contacted','responded','planned','in_progress','shipped','declined'); exception when duplicate_object then null; end $$;
do $$ begin create type reaction_kind as enum ('supportive','love','fire','helpful','agree','not_enough'); exception when duplicate_object then null; end $$;

create table if not exists companies (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, website text, logo_url text, description text, contact_email text, created_at timestamptz not null default now());
create table if not exists products (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, slug text not null, created_at timestamptz not null default now(), unique(company_id,slug));
create table if not exists pitches (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), product_id uuid not null references products(id), title text not null check(char_length(title) between 8 and 140), slug text not null, body text not null check(char_length(body) between 20 and 2000), suggested_slug text, status pitch_status not null default 'pending', support_count bigint not null default 0, submitter_note text, moderation_note text, email_milestones_sent int[] not null default '{}', last_email_milestone int, contacted_at timestamptz, company_response text, company_response_verified boolean not null default false, responded_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,product_id,slug));
create table if not exists supports (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, fingerprint text not null, created_at timestamptz not null default now(), unique(pitch_id,fingerprint));
create table if not exists pitch_reactions (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, fingerprint text not null, reaction reaction_kind not null, created_at timestamptz not null default now(), unique(pitch_id,fingerprint));
create table if not exists comments (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, fingerprint text not null, body text not null check(char_length(body) between 1 and 1000), display_name text, approved boolean not null default false, created_at timestamptz not null default now());
create table if not exists company_responses (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, body text not null, verified boolean not null default false, received_at timestamptz, published_at timestamptz, created_at timestamptz not null default now());
create table if not exists email_milestone_events (id uuid primary key default gen_random_uuid(), pitch_id uuid not null references pitches(id) on delete cascade, milestone int not null check(milestone in(1,25,50,100,500,1000)), sent_at timestamptz not null default now(), notes text, unique(pitch_id,milestone));
create table if not exists admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());

alter table companies enable row level security; alter table products enable row level security; alter table pitches enable row level security; alter table supports enable row level security; alter table pitch_reactions enable row level security; alter table comments enable row level security; alter table company_responses enable row level security; alter table email_milestone_events enable row level security; alter table admin_users enable row level security;

create or replace function is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from admin_users where user_id=auth.uid()); $$;
create or replace function increment_support(p_pitch_id uuid,p_fingerprint text) returns bigint language plpgsql security definer set search_path=public as $$ declare n bigint; begin insert into supports(pitch_id,fingerprint) values(p_pitch_id,p_fingerprint) on conflict(pitch_id,fingerprint) do nothing; if found then update pitches set support_count=support_count+1,updated_at=now() where id=p_pitch_id returning support_count into n; else select support_count into n from pitches where id=p_pitch_id; end if; return n; end; $$;
create or replace function submit_pitch(p_company_id uuid,p_product_id uuid,p_title text,p_body text,p_suggested_slug text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare n uuid; s text; begin s=lower(trim(regexp_replace(coalesce(nullif(p_suggested_slug,''),p_title),'[^a-zA-Z0-9]+','-','g'))); s=regexp_replace(s,'(^-+|-+$)','','g'); if s='' then s='pitch'; end if; insert into pitches(company_id,product_id,title,body,suggested_slug,slug) values(p_company_id,p_product_id,trim(p_title),trim(p_body),nullif(trim(p_suggested_slug),''),s) returning id into n; return n; end; $$;
create or replace function publish_pitch(p_id uuid,p_slug text,p_status pitch_status default 'open') returns boolean language plpgsql security definer set search_path=public as $$ begin if not is_admin() then raise exception 'not authorized'; end if; update pitches set slug=lower(trim(regexp_replace(regexp_replace(p_slug,'[^a-zA-Z0-9]+','-','g'),'(^-+|-+$)','','g'))),status=p_status,updated_at=now() where id=p_id; return found; end; $$;
revoke all on function is_admin() from public; grant execute on function is_admin() to authenticated;
revoke all on function increment_support(uuid,text) from public; grant execute on function increment_support(uuid,text) to anon,authenticated;
revoke all on function submit_pitch(uuid,uuid,text,text,text) from public; grant execute on function submit_pitch(uuid,uuid,text,text,text) to anon,authenticated;
revoke all on function publish_pitch(uuid,text,pitch_status) from public; grant execute on function publish_pitch(uuid,text,pitch_status) to authenticated;

-- Public policies
 drop policy if exists public_companies_read on companies; create policy public_companies_read on companies for select using(true);
 drop policy if exists public_products_read on products; create policy public_products_read on products for select using(true);
 drop policy if exists public_pitches_read on pitches; create policy public_pitches_read on pitches for select using(status <> 'pending');
 drop policy if exists public_support_insert on supports; create policy public_support_insert on supports for insert with check(true);
 drop policy if exists public_reaction_insert on pitch_reactions; create policy public_reaction_insert on pitch_reactions for insert with check(true);
 drop policy if exists public_comment_insert on comments; create policy public_comment_insert on comments for insert with check(true);
 drop policy if exists public_comments_read on comments; create policy public_comments_read on comments for select using(approved=true);
 drop policy if exists public_responses_read on company_responses; create policy public_responses_read on company_responses for select using(verified=true and published_at is not null);
 drop policy if exists admin_self_read on admin_users; create policy admin_self_read on admin_users for select to authenticated using(user_id=auth.uid());
 drop policy if exists admin_companies_write on companies; create policy admin_companies_write on companies for all to authenticated using(is_admin()) with check(is_admin());
 drop policy if exists admin_products_write on products; create policy admin_products_write on products for all to authenticated using(is_admin()) with check(is_admin());
 drop policy if exists admin_pitches_write on pitches; create policy admin_pitches_write on pitches for all to authenticated using(is_admin()) with check(is_admin());
 drop policy if exists admin_responses_write on company_responses; create policy admin_responses_write on company_responses for all to authenticated using(is_admin()) with check(is_admin());
 drop policy if exists admin_milestones_write on email_milestone_events; create policy admin_milestones_write on email_milestone_events for all to authenticated using(is_admin()) with check(is_admin());
 drop policy if exists admin_comments_write on comments; create policy admin_comments_write on comments for all to authenticated using(is_admin()) with check(is_admin());

insert into companies(name,slug,description) values('Google','google','Products we use every day.'),('Spotify','spotify','Music and audio products.'),('WhatsApp','whatsapp','Simple, reliable private messaging.') on conflict(slug) do nothing;
insert into products(company_id,name,slug) select c.id,x.name,x.slug from companies c join(values('Google','Google Contacts','contacts'),('Spotify','Spotify','spotify'),('WhatsApp','WhatsApp','whatsapp')) x(company_name,name,slug) on x.company_name=c.name on conflict(company_id,slug) do nothing;
