import { useSeo } from "@/lib/seo";

interface Section {
  heading: string;
  paragraphs: string[];
}

function LegalPage({
  eyebrow,
  title,
  intro,
  sections,
  seo,
}: {
  eyebrow: string;
  title: string;
  intro: string;
  sections: Section[];
  seo: { title: string; description: string; path: string };
}) {
  useSeo(seo);

  return (
    <div className="shell max-w-3xl py-14">
      <p className="eyebrow">{eyebrow}</p>
      <h1 className="display mt-3 text-3xl md:text-4xl">{title}</h1>
      <p className="reading mt-5 text-[15px] leading-relaxed text-muted-foreground">{intro}</p>

      <div className="mt-10 space-y-10">
        {sections.map((section) => (
          <section key={section.heading}>
            <h2 className="text-sm font-semibold tracking-tight text-foreground">
              {section.heading}
            </h2>
            <div className="reading mt-3 space-y-3 text-[15px] leading-relaxed text-muted-foreground">
              {section.paragraphs.map((text) => (
                <p key={text.slice(0, 40)}>{text}</p>
              ))}
            </div>
          </section>
        ))}
      </div>

      <p className="mt-12 border-t border-border pt-6 text-xs text-subtle-foreground">
        Questions about this page? Write to iamsaitejathanniru@gmail.com.
      </p>
    </div>
  );
}

export function Terms() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms of use"
      intro="By using PitchMe you agree to the terms below. They exist to keep the platform useful and fair for everyone."
      seo={{
        title: "Terms of use | PitchMe",
        description:
          "The terms that govern posting pitches, supporting ideas, and commenting on PitchMe.",
        path: "/terms",
      }}
      sections={[
        {
          heading: "Using the platform",
          paragraphs: [
            "PitchMe is free to use and requires no account. You may submit pitches, support pitches, react, and comment.",
            "You are responsible for what you post. Do not post confidential information, personal data about other people, or anything you do not have the right to share.",
          ],
        },
        {
          heading: "Your content",
          paragraphs: [
            "You keep ownership of what you write. By posting you grant PitchMe a non exclusive right to display, reproduce, and share that content on the platform and when contacting the company a pitch is addressed to.",
            "Submissions are reviewed before publication and may be edited for clarity, formatting, or safety, or declined without notice.",
          ],
        },
        {
          heading: "No guarantees",
          paragraphs: [
            "PitchMe is provided as is. We do not promise that a company will read, answer, or act on any pitch, and we cannot guarantee uninterrupted availability.",
            "Company responses are published as received. We verify who sent them, not whether their contents are accurate.",
          ],
        },
        {
          heading: "Termination",
          paragraphs: [
            "We may remove any content or restrict access from any browser or address that abuses the platform, manipulates support counts, or breaks these terms.",
          ],
        },
      ]}
    />
  );
}

export function Privacy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy"
      intro="PitchMe is built to work without accounts, so it collects as little as possible about the people who use it."
      seo={{
        title: "Privacy | PitchMe",
        description:
          "What PitchMe stores, why it stores it, and how anonymous participation works without accounts.",
        path: "/privacy",
      }}
      sections={[
        {
          heading: "What is stored",
          paragraphs: [
            "When you support or react to a pitch, a random identifier generated by your browser is stored alongside that action. It is not linked to your name, email, or account, and it exists only to stop the same browser supporting a pitch repeatedly.",
            "Pitches and comments are stored with their text and timestamp. Do not include personal details in them.",
          ],
        },
        {
          heading: "What is not stored",
          paragraphs: [
            "There are no user accounts for the public site, no advertising trackers, and no third party analytics profiles built from your activity.",
          ],
        },
        {
          heading: "Local storage",
          paragraphs: [
            "The anonymous identifier lives in your browser local storage. Clearing site data removes it, after which the site treats you as a new visitor.",
          ],
        },
        {
          heading: "Removal requests",
          paragraphs: [
            "Ask for a pitch or comment to be removed by writing to iamsaitejathanniru@gmail.com with a link to it.",
          ],
        },
      ]}
    />
  );
}

export function CommunityGuidelines() {
  return (
    <LegalPage
      eyebrow="Community"
      title="Community guidelines"
      intro="A good pitch is specific, honest, and useful to the person who has to build it. These guidelines keep the signal high."
      seo={{
        title: "Community guidelines | PitchMe",
        description:
          "How to write a pitch that gathers support, and what gets removed by moderators on PitchMe.",
        path: "/community-guidelines",
      }}
      sections={[
        {
          heading: "Write a strong pitch",
          paragraphs: [
            "Describe the problem before the solution. Say who is affected, how often, and what you do today as a workaround.",
            "One idea per pitch. Bundled requests are hard to support and harder for a company to act on.",
          ],
        },
        {
          heading: "Support honestly",
          paragraphs: [
            "Support pitches you genuinely want. Using multiple browsers or automation to inflate a count devalues every number on the site and will be reversed.",
          ],
        },
        {
          heading: "What gets removed",
          paragraphs: [
            "Harassment, hate speech, and personal attacks. Spam, referral links, and product promotion. Confidential or leaked material. Personal data about anyone.",
            "Support tickets. If you need help with your own account, contact the company directly.",
          ],
        },
        {
          heading: "Moderation decisions",
          paragraphs: [
            "Moderation is manual and imperfect. If you think something was removed in error, write to iamsaitejathanniru@gmail.com and it will be reviewed again.",
          ],
        },
      ]}
    />
  );
}

export function CopyrightTrademark() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Copyright and trademarks"
      intro="PitchMe references products by name and logo so people know which product a pitch is about. Nothing more is implied."
      seo={{
        title: "Copyright and trademarks | PitchMe",
        description:
          "How PitchMe uses company names and logos, our attribution sources, and how to request a change.",
        path: "/copyright-trademark",
      }}
      sections={[
        {
          heading: "Trademarks",
          paragraphs: [
            "All company names, product names, trademarks, and logos are the property of their respective owners. Their use here is nominative: it identifies the product a pitch concerns.",
            "PitchMe is an independent community project. It is not affiliated with, sponsored by, or endorsed by any company listed on the site.",
          ],
        },
        {
          heading: "Logo sources",
          paragraphs: [
            "Most brand marks are served from Simple Icons, a public collection of brand logos. Where a different source is used, it is credited on the company profile page.",
            "Logos are shown at small sizes, unmodified apart from colour needed for legibility on a dark background, and never as part of PitchMe branding.",
          ],
        },
        {
          heading: "User content",
          paragraphs: [
            "Pitches and comments are written by members of the public and remain the work of their authors. They do not represent the views of the companies mentioned.",
          ],
        },
        {
          heading: "Requesting a change or removal",
          paragraphs: [
            "Rights holders can ask for a logo, name, or piece of content to be corrected or removed by writing to iamsaitejathanniru@gmail.com with the relevant link. Requests are handled promptly.",
          ],
        },
      ]}
    />
  );
}
