import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Flame, LockKeyhole, Search, ShieldCheck, Sparkles, ThumbsUp, X } from 'lucide-react';
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { createClient } from '@supabase/supabase-js';
import type { Company, Pitch, Product, PitchStatus } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
const MILESTONES = [1, 25, 50, 100, 500, 1000];

function getFingerprint() {
  const key = 'pitchme-anon-id';
  let value = localStorage.getItem(key);
  if (!value) { value = typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; localStorage.setItem(key, value); }
  return value;
}
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
function formatNumber(value: number) { return new Intl.NumberFormat('en-US').format(value); }

export default function App() {
  return <Routes>
    <Route path="/" element={<Home />} />
    <Route path="/discover" element={<Home />} />
    <Route path="/pitch/:company/:product/:slug" element={<PitchPage />} />
    <Route path="/submit" element={<SubmitPitch />} />
    <Route path="/admin" element={<Admin />} />
    <Route path="*" element={<NotFound />} />
  </Routes>;
}

function Layout({ children }: { children: React.ReactNode }) {
  return <div className="app-shell">
    <header className="topbar"><Link to="/" className="brand">pitchme<span>.</span></Link><nav><Link to="/">Discover</Link><Link to="/submit">Pitch a feature</Link></nav></header>
    <main>{children}</main>
    <footer><div><strong>pitchme.</strong> Make products better.</div><div className="footer-note">Independent community feedback. No company affiliation implied.</div></footer>
  </div>;
}

function useDiscovery() {
  const [pitches, setPitches] = useState<Pitch[]>([]); const [companies, setCompanies] = useState<Company[]>([]); const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!supabase) return; Promise.all([
    supabase.from('pitches').select('*').neq('status', 'pending').order('support_count', { ascending: false }).limit(50),
    supabase.from('companies').select('*').order('name'),
    supabase.from('products').select('*').order('name')
  ]).then(([p, c, pr]) => { setPitches((p.data ?? []) as Pitch[]); setCompanies((c.data ?? []) as Company[]); setProducts((pr.data ?? []) as Product[]); }).finally(() => setLoading(false)); }, []);
  return { pitches, companies, products, loading };
}

function Home() {
  const { pitches, companies, products, loading } = useDiscovery(); const [query, setQuery] = useState('');
  const filtered = useMemo(() => pitches.filter((p) => `${p.title} ${p.body} ${companies.find(c => c.id === p.company_id)?.name ?? ''} ${products.find(pr => pr.id === p.product_id)?.name ?? ''}`.toLowerCase().includes(query.toLowerCase().trim())), [pitches, companies, products, query]);
  return <Layout>
    <section className="hero"><div className="eyebrow"><Sparkles size={15} /> Public product feedback</div><h1>Something missing?<br /><span>Pitch it.</span></h1><p className="hero-copy">Turn a product idea into a public request. Get people behind it. When a meaningful supporter milestone is reached, we contact the company manually and keep the response in the open.</p><div className="hero-actions"><Link className="button primary" to="/submit">Pitch a feature <ArrowRight size={18} /></Link><a className="button ghost" href="#discover">Explore pitches</a></div></section>
    <section id="discover" className="discover-section"><div className="section-head"><div><div className="section-kicker">Discover</div><h2>What people want changed.</h2></div><div className="searchbox"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search products or pitches" /></div></div>{loading ? <Empty text="Loading pitches..." /> : filtered.length ? <div className="pitch-grid">{filtered.map(p => <PitchCard key={p.id} pitch={p} company={companies.find(c => c.id === p.company_id)} product={products.find(pr => pr.id === p.product_id)} />)}</div> : <Empty text="No pitches match that search." />}</section>
    <section className="how-section"><div className="section-kicker">How it works</div><div className="steps"><Step number="01" title="Pitch it" text="Describe what is missing. No account needed." /><Step number="02" title="Get support" text="People who want the same thing can support it without signing up." /><Step number="03" title="Reach a milestone" text="PitchMe records the 1, 25, 50, 100, 500 and 1000 supporter milestones." /><Step number="04" title="Hear back" text="When a company replies, the response can become part of the public record." /></div></section>
  </Layout>;
}

function Empty({ text }: { text: string }) { return <div className="comments-placeholder"><p>{text}</p></div>; }
function PitchCard({ pitch, company, product }: { pitch: Pitch; company?: Company; product?: Product }) { return <Link to={`/pitch/${company?.slug ?? 'company'}/${product?.slug ?? 'product'}/${pitch.slug}`} className="pitch-card"><div className="card-top"><span className="pill">{product?.name ?? 'Product'}</span><StatusBadge status={pitch.status} /></div><h3>{pitch.title}</h3><p>{pitch.body}</p><div className="card-footer"><span className="support-count"><Flame size={18} /> {formatNumber(pitch.support_count)} supporters</span><span>Open pitch <ArrowRight size={16} /></span></div></Link>; }

function PitchPage() {
  const { company, product, slug } = useParams(); const [pitch, setPitch] = useState<Pitch | null>(null); const [companyRecord, setCompany] = useState<Company | null>(null); const [productRecord, setProduct] = useState<Product | null>(null); const [supported, setSupported] = useState(false); const [reaction, setReaction] = useState<string | null>(null); const [comment, setComment] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { if (!supabase) return; void (async () => { const { data: c } = await supabase.from('companies').select('*').eq('slug', company).maybeSingle(); const { data: p } = await supabase.from('products').select('*').eq('slug', product).maybeSingle(); if (!c || !p) return; const { data: pitchData } = await supabase.from('pitches').select('*').eq('company_id', c.id).eq('product_id', p.id).eq('slug', slug).neq('status', 'pending').maybeSingle(); if (pitchData) { setPitch(pitchData as Pitch); setCompany(c as Company); setProduct(p as Product); } })(); }, [company, product, slug]);
  if (!pitch) return <Layout><div className="success-state"><div className="section-kicker">Pitch</div><h1>Finding that pitch.</h1><p>Loading the public request.</p></div></Layout>;
  const support = async () => { if (!supabase || supported) return; const { data, error } = await supabase.rpc('increment_support', { p_pitch_id: pitch.id, p_fingerprint: getFingerprint() }); if (!error) { setPitch({ ...pitch, support_count: Number(data) }); setSupported(true); } };
  const react = async (kind: string) => { if (!supabase) return; const { error } = await supabase.from('pitch_reactions').upsert({ pitch_id: pitch.id, fingerprint: getFingerprint(), reaction: kind }, { onConflict: 'pitch_id,fingerprint' }); if (!error) setReaction(kind); };
  const addComment = async (e: FormEvent) => { e.preventDefault(); if (!supabase || !comment.trim()) return; const { error } = await supabase.from('comments').insert({ pitch_id: pitch.id, fingerprint: getFingerprint(), body: comment.trim(), approved: false }); setNotice(error ? 'Comment could not be submitted.' : 'Comment submitted for review.'); if (!error) setComment(''); };
  return <Layout><div className="page-wrap"><Link to="/" className="back-link">← Back to discovery</Link><div className="pitch-detail"><div className="detail-main"><div className="detail-kicker">{companyRecord?.name} / {productRecord?.name}</div><h1>{pitch.title}</h1><p className="detail-body">{pitch.body}</p><div className="support-box"><div><strong>{formatNumber(pitch.support_count)}</strong><span>people want this</span></div><button className="button primary support-button" onClick={support}>{supported ? <Check size={18} /> : <ThumbsUp size={18} />} {supported ? 'Supported' : 'I want this too'}</button></div><div className="status-timeline"><Timeline label="Pitch published" active /><Timeline label="Community support" active={pitch.support_count >= 25} meta="Public support count keeps growing." /><Timeline label="Company contacted" active={(pitch.email_milestones_sent ?? []).length > 0} meta={(pitch.email_milestones_sent ?? []).length ? `Milestones: ${pitch.email_milestones_sent.join(', ')}` : 'Waiting for a milestone.'} /><Timeline label="Company response" active={Boolean(pitch.company_response)} /></div>{pitch.company_response ? <section className="response-card"><div className="response-label"><ShieldCheck size={17} /> Company response</div><p>{pitch.company_response}</p><div className="response-date">Published {pitch.responded_at ? new Date(pitch.responded_at).toLocaleDateString() : ''}</div><div className="reaction-row">{[['helpful','Helpful'],['agree','I agree'],['not_enough','Not enough']].map(([v,l]) => <button key={v} className={reaction === v ? 'active' : ''} onClick={() => react(v)}>{l}</button>)}</div></section> : <div className="comments-placeholder"><p>No company response yet. This section will show it when one is received and verified.</p></div>}<section className="comments-placeholder"><div className="section-kicker">Community</div><h2>What people are saying</h2><form className="pitch-form" onSubmit={addComment}><textarea value={comment} onChange={e => setComment(e.target.value)} rows={4} maxLength={1000} placeholder="Add something useful to the discussion..." /><button className="button ghost submit-button" disabled={!comment.trim()}>Post comment</button></form>{notice && <p>{notice}</p>}</section></div></div></div></Layout>;
}

function SubmitPitch() {
  const navigate = useNavigate(); const [companies, setCompanies] = useState<Company[]>([]); const [products, setProducts] = useState<Product[]>([]); const [companyId, setCompanyId] = useState(''); const [productId, setProductId] = useState(''); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [suggestedSlug, setSuggestedSlug] = useState(''); const [accepted, setAccepted] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!supabase) return; void Promise.all([supabase.from('companies').select('*').order('name'), supabase.from('products').select('*').order('name')]).then(([c,p]) => { const cs=(c.data??[]) as Company[]; setCompanies(cs); setProducts((p.data??[]) as Product[]); if (cs[0]) setCompanyId(cs[0].id); }); }, []);
  const availableProducts = products.filter(p => p.company_id === companyId);
  useEffect(() => { setProductId(availableProducts[0]?.id ?? ''); }, [companyId, products.length]);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); if (!supabase || !accepted || !companyId || !productId) return; const { data, error: err } = await supabase.rpc('submit_pitch', { p_company_id: companyId, p_product_id: productId, p_title: title.trim(), p_body: body.trim(), p_suggested_slug: suggestedSlug || null }); if (err || !data) setError(err?.message ?? 'Could not submit the pitch.'); else setDone(true); };
  if (done) return <Layout><div className="success-state"><div className="success-icon"><Check /></div><div className="section-kicker">Pitch received</div><h1>Your idea is in.</h1><p>It will be reviewed before becoming public. There is no account to manage.</p><button className="button primary" onClick={() => navigate('/')}>Back to PitchMe</button></div></Layout>;
  return <Layout><div className="form-page"><div className="section-kicker">Create a pitch</div><h1>Give a product<br /><span>something better.</span></h1><p className="form-intro">No account. No followers. Just a useful idea and the people who agree with you.</p><form onSubmit={submit} className="pitch-form"><label>Company<select value={companyId} onChange={e => setCompanyId(e.target.value)}>{companies.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Product<select value={productId} onChange={e => setProductId(e.target.value)}>{availableProducts.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>What should change?<input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Add Speed Dial to Contacts" maxLength={140} /></label><label>Preferred URL slug <span style={{fontWeight:400,color:'#71717a'}}>(optional - admin has final say)</span><input value={suggestedSlug} onChange={e => setSuggestedSlug(slugify(e.target.value))} placeholder="speed-dial" maxLength={80} /></label><label>Why does this matter?<textarea value={body} onChange={e => setBody(e.target.value)} rows={7} placeholder="Explain the problem and what would make the product better." maxLength={2000} /></label><label className="consent"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} /><span>I understand this will be reviewed and, if accepted, publicly posted. I will not submit private, confidential, or abusive content.</span></label>{error && <p style={{color:'#fda4af'}}>{error}</p>}<button className="button primary submit-button" disabled={!accepted || title.trim().length < 8 || body.trim().length < 20 || !companyId || !productId}>Submit pitch <ArrowRight size={18} /></button></form></div></Layout>;
}

function Admin() {
  const [session, setSession] = useState<any>(null); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [pitches, setPitches] = useState<Pitch[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: listener } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (session) void load(); }, [session]);
  async function load() { if (!supabase) return; const { data } = await supabase.from('pitches').select('*, company:companies(*), product:products(*)').order('created_at', { ascending: false }); setPitches((data ?? []) as Pitch[]); }
  async function login(e: FormEvent) { e.preventDefault(); if (!supabase) return; const { error: err } = await supabase.auth.signInWithPassword({ email, password }); if (err) setError(err.message); }
  async function approve(pitch: Pitch) { if (!supabase) return; const { error: err } = await supabase.rpc('publish_pitch', { p_id: pitch.id, p_slug: pitch.suggested_slug || slugify(pitch.title), p_status: 'open' }); if (err) setNotice(err.message); else { setNotice('Pitch published.'); await load(); } }
  async function decline(pitch: Pitch) { if (!supabase) return; const { error: err } = await supabase.rpc('publish_pitch', { p_id: pitch.id, p_slug: pitch.suggested_slug || slugify(pitch.title), p_status: 'declined' }); if (err) setNotice(err.message); else { setNotice('Pitch declined.'); await load(); } }
  async function recordMilestone(pitch: Pitch, milestone: number) { if (!supabase || (pitch.email_milestones_sent ?? []).includes(milestone) || pitch.support_count < milestone) return; const { error: insertError } = await supabase.from('email_milestone_events').insert({ pitch_id: pitch.id, milestone, notes: 'Manually sent by admin' }); if (insertError) { setNotice(insertError.message); return; } const next = [...(pitch.email_milestones_sent ?? []), milestone].sort((a,b) => a-b); const { error: updateError } = await supabase.from('pitches').update({ email_milestones_sent: next, last_email_milestone: milestone, contacted_at: new Date().toISOString(), status: 'contacted' }).eq('id', pitch.id); setNotice(updateError ? updateError.message : `Recorded ${milestone} supporter outreach.`); await load(); }
  if (!session) return <Layout><div className="form-page"><div className="section-kicker"><LockKeyhole size={14} /> Private</div><h1>Admin access.</h1><p className="form-intro">This page is intentionally unlinked from the public navigation.</p><form className="pitch-form" onSubmit={login}><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p style={{color:'#fda4af'}}>{error}</p>}<button className="button primary">Sign in</button></form></div></Layout>;
  const pending = pitches.filter(p => p.status === 'pending'); const published = pitches.filter(p => p.status !== 'pending');
  return <Layout><div className="admin-page"><div className="section-kicker"><ShieldCheck size={14} /> Admin</div><h1>PitchMe control room.</h1><p className="form-intro">Review submissions, decide what becomes public, and record manual company outreach. This area is only available to the admin account.</p>{notice && <div className="admin-message">{notice}</div>}<div className="admin-grid"><div className="admin-card"><span>All pitches</span><strong>{pitches.length}</strong><small>Database records.</small></div><div className="admin-card"><span>Needs review</span><strong>{pending.length}</strong><small>Awaiting your decision.</small></div><div className="admin-card"><span>Published</span><strong>{published.length}</strong><small>Visible to everyone.</small></div></div><div className="milestone-panel"><h2>Outreach milestones</h2><div className="milestones">{MILESTONES.map(n => <div key={n}><b>{n}</b><span>supporters</span></div>)}</div><p>Support counts remain continuous. Only these milestones trigger your manual outreach workflow.</p></div><div className="admin-list">{pitches.map(p => <article className="admin-pitch" key={p.id}><div><div className="admin-pitch-meta">{p.company?.name} / {p.product?.name} · {p.status}</div><h3>{p.title}</h3><p>{p.body}</p><div className="admin-support">{formatNumber(p.support_count)} supporters</div></div><div className="admin-actions">{p.status === 'pending' ? <><button className="button primary" onClick={() => approve(p)}>Publish</button><button className="button ghost" onClick={() => decline(p)}>Decline</button></> : <div className="milestone-buttons">{MILESTONES.map(n => <button key={n} disabled={(p.email_milestones_sent ?? []).includes(n) || p.support_count < n} onClick={() => recordMilestone(p, n)}>{n} {(p.email_milestones_sent ?? []).includes(n) ? 'sent' : 'send'}</button>)}</div>}</div></article>)}</div></div></Layout>;
}

function Timeline({ label, active, meta }: { label: string; active?: boolean; meta?: string }) { return <div className={`timeline-item ${active ? 'active' : ''}`}><div className="timeline-dot">{active ? <Check size={13} /> : <X size={13} />}</div><div><strong>{label}</strong>{meta && <small>{meta}</small>}</div></div>; }
function StatusBadge({ status }: { status: PitchStatus }) { const labels: Record<PitchStatus, string> = { pending:'Pending', open:'Open', contacted:'Contacted', responded:'Responded', planned:'Planned', in_progress:'In progress', shipped:'Shipped', declined:'Declined' }; return <span className={`status status-${status}`}>{labels[status]}</span>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="step"><span>{number}</span><h3>{title}</h3><p>{text}</p></div>; }
function NotFound() { return <Layout><div className="success-state"><div className="section-kicker">404</div><h1>That pitch is not here.</h1><p>Maybe it has not been published yet.</p><Link className="button primary" to="/">Discover pitches</Link></div></Layout>; }
