const LOGO_BASE = 'https://cdn.simpleicons.org/';
const COMPANY_LOGOS: Record<string, string> = {
  openai:`${LOGO_BASE}openai`, anthropic:`${LOGO_BASE}anthropic`, netflix:`${LOGO_BASE}netflix`, google:`${LOGO_BASE}google`, apple:`${LOGO_BASE}apple`, microsoft:`${LOGO_BASE}microsoft`, github:`${LOGO_BASE}github`, spotify:`${LOGO_BASE}spotify`, whatsapp:`${LOGO_BASE}whatsapp`, notion:`${LOGO_BASE}notion`, figma:`${LOGO_BASE}figma`, discord:`${LOGO_BASE}discord`, slack:`${LOGO_BASE}slack`, youtube:`${LOGO_BASE}youtube`, amazon:`${LOGO_BASE}amazon`, duolingo:`${LOGO_BASE}duolingo`, linear:`${LOGO_BASE}linear`, canva:`${LOGO_BASE}canva`, dropbox:`${LOGO_BASE}dropbox`, zoom:`${LOGO_BASE}zoom`,
};
function slugFromHref(href:string){return href.match(/^\/company\/([^/?#]+)/)?.[1]??null;}
function addLogo(target:Element,src:string,label:string,className:string){if(target.querySelector(`img.${className}`))return;const img=document.createElement('img');img.className=className;img.src=src;img.alt=`${label} logo`;img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.remove(),{once:true});target.prepend(img);}
function enhance(){document.querySelectorAll<HTMLAnchorElement>('a[href^="/company/"]').forEach(link=>{const slug=slugFromHref(link.getAttribute('href')??'');const src=slug?COMPANY_LOGOS[slug]:undefined;if(!src)return;const card=link.closest('.pitch-card');if(card){card.classList.add('has-company-logo');addLogo(card,src,slug,'company-logo-card');}const kicker=link.closest('.detail-kicker');if(kicker)addLogo(kicker,src,slug,'company-logo-inline');});const match=window.location.pathname.match(/^\/company\/([^/?#]+)/);if(match){const src=COMPANY_LOGOS[match[1]];const heading=document.querySelector<HTMLElement>('.pitch-detail > h1');if(src&&heading)addLogo(heading.parentElement??heading,src,match[1],'company-logo-heading');}}
function attribution(){const footer=document.querySelector('footer');if(!footer||footer.querySelector('.brand-attribution'))return;const el=document.createElement('div');el.className='brand-attribution';el.textContent='Company names, product names, trademarks, and logos belong to their respective owners. Logos are shown for identification only. PitchMe is independent and not affiliated with or endorsed by the companies shown. Logos provided by Simple Icons.';footer.appendChild(el);}
export function initCompanyBranding(){const run=()=>{enhance();attribution();};run();const observer=new MutationObserver(run);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('popstate',run);return()=>{observer.disconnect();window.removeEventListener('popstate',run);};}
