import { Link } from 'react-router-dom';

export function LegalLayout({ title, kicker, children }: { title: string; kicker?: string; children: React.ReactNode }) {
  return <div className="page-wrap legal-page"><Link to="/" className="back-link">Back to PitchMe</Link><div className="section-kicker" style={{ marginTop: 38 }}>{kicker ?? 'Legal'}</div><h1>{title}</h1><div className="legal-copy">{children}</div></div>;
}

export function AboutPage() { return <LegalLayout title="About PitchMe" kicker="About"><p><strong>PitchMe</strong> is an independent community project for public product feedback. People can describe something they want changed, support requests they agree with, and see when PitchMe has contacted a company and whether a response has been published.</p><h2>What PitchMe is</h2><p>PitchMe is a community feedback layer. It is not operated by the companies, products, or brands shown on the site.</p><h2>What PitchMe is not</h2><p>PitchMe is not an official support channel, customer-service department, product roadmap, legal service, or promise that a company will respond or implement a request.</p><h2>Contact</h2><p>Questions, corrections, copyright concerns, abuse reports, or privacy requests can be sent to <a href="mailto:iamsaitejathanniru@gmail.com">iamsaitejathanniru@gmail.com</a>.</p><h2>Source</h2><p>Project code: <a href="https://github.com/iam-saiteja/pitchme" target="_blank" rel="noreferrer">github.com/iam-saiteja/pitchme</a>.</p></LegalLayout>; }

export function TermsPage() { return <LegalLayout title="Terms of Use"><p>Last updated: August 17, 2026.</p><p>By using PitchMe, you agree to use the site lawfully and responsibly. These terms are plain-language site rules, not legal advice.</p><h2>Community submissions</h2><p>You are responsible for what you submit. Do not post private information, passwords, confidential business information, threats, harassment, unlawful material, spam, impersonation, or material you do not have the right to publish.</p><h2>Moderation</h2><p>PitchMe may review, reject, edit for clarity, unpublish, or remove submissions, comments, reactions, and other material where content violates these rules or creates legal, safety, privacy, or abuse concerns.</p><h2>Support counts</h2><p>Support counts are community signals, not verified market research. PitchMe may limit or investigate automated activity, manipulation, or repeated attempts to distort a request.</p><h2>Company responses</h2><p>A company response is shown as official only after PitchMe reviews the source and marks it verified. PitchMe does not guarantee that a company will read, acknowledge, or implement a request.</p><h2>Third-party names and marks</h2><p>Company names, product names, trademarks, and logos belong to their respective owners. Their appearance on PitchMe does not imply sponsorship, affiliation, partnership, or endorsement.</p><h2>Availability</h2><p>PitchMe is experimental and may change, become unavailable, or remove functionality without notice.</p><h2>Contact</h2><p><a href="mailto:iamsaitejathanniru@gmail.com">iamsaitejathanniru@gmail.com</a></p></LegalLayout>; }

export function PrivacyPage() { return <LegalLayout title="Privacy Policy"><p>Last updated: August 17, 2026.</p><p>PitchMe is designed to work without ordinary user accounts. We still process limited information needed to operate, protect, and moderate the service.</p><h2>Information we collect</h2><p><strong>Pitches and comments:</strong> Content you submit, timestamps, and moderation state are stored so published requests can be displayed and moderated.</p><p><strong>Anonymous interaction identifier:</strong> PitchMe generates a random browser identifier so a visitor can support a pitch once and keep that state across refreshes. It is not intended to identify you by name.</p><p><strong>Administrator account data:</strong> Admin authentication is handled through Supabase and is separate from ordinary community participation.</p><p><strong>Technical information:</strong> Cloudflare and other infrastructure providers may process normal technical information such as IP address, browser information, request logs, and security telemetry.</p><h2>Why we use it</h2><p>We use information to publish and moderate community content, maintain anonymous support limits, protect the service from abuse, operate administration tools, and troubleshoot reliability and security issues.</p><h2>Third-party services</h2><p>PitchMe uses Cloudflare for hosting and delivery and Supabase for database and authentication infrastructure. Company logo assets are requested from Simple Icons.</p><h2>Retention</h2><p>We aim to keep only what is reasonably needed for operation, moderation, security, legal compliance, and the public history of published pitches. Published community content may remain public unless removed under our moderation or legal processes.</p><h2>Your requests</h2><p>For privacy, correction, or deletion requests, email <a href="mailto:iamsaitejathanniru@gmail.com">iamsaitejathanniru@gmail.com</a>. Do not send passwords or other sensitive secrets.</p><h2>Legal framework</h2><p>PitchMe is being developed in India and will update its privacy practices as applicable data-protection and online-platform requirements take effect. This page is not a substitute for legal advice.</p></LegalLayout>; }

export function GuidelinesPage() { return <LegalLayout title="Community Guidelines"><p>PitchMe works only when people can disagree without turning the site into a spam wall. These rules apply to pitches, comments, reactions, and other community content.</p><h2>Good submissions</h2><p>Be specific about the problem. Explain who it affects, what could improve, and why the change matters.</p><h2>Not allowed</h2><ul><li>Threats, harassment, hate, or targeted abuse.</li><li>Private or sensitive personal information.</li><li>Confidential company information or leaked credentials.</li><li>Spam, scams, malware, or automated abuse.</li><li>Impersonation or misleading claims of official endorsement.</li><li>Manipulation of support counts or coordinated fraudulent activity.</li></ul><h2>Moderation</h2><p>Submitted comments are reviewed before publication. PitchMe may reject or remove content that violates these rules or creates legal, privacy, safety, or operational concerns.</p><h2>Corrections</h2><p>For inaccurate, copyrighted, impersonating, or otherwise problematic material, contact <a href="mailto:iamsaitejathanniru@gmail.com">iamsaitejathanniru@gmail.com</a>.</p></LegalLayout>; }

export function TrademarkPage() { return <LegalLayout title="Copyright & Trademark"><p>PitchMe is an independent project. The PitchMe name, interface, and original content are separate from the third-party brands shown on the site.</p><h2>Third-party marks</h2><p>Company names, product names, logos, and trademarks displayed on PitchMe belong to their respective owners and are used for identification and discussion of those products. Their display does not imply affiliation, sponsorship, authorization, or endorsement.</p><h2>Logo source</h2><p>Company logos are provided through Simple Icons. PitchMe does not claim ownership of third-party logos. Source attribution is provided for transparency.</p><h2>User content</h2><p>By submitting content, you represent that you have the right to submit it and that it does not contain confidential or unlawful material. If you believe content infringes your rights, contact us with the relevant URL and supporting details.</p><h2>Contact</h2><p><a href="mailto:iamsaitejathanniru@gmail.com">iamsaitejathanniru@gmail.com</a></p></LegalLayout>; }
